name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Login realizado con exito"

    - name: Build the Docker image
      run: |
        echo "Building the Docker image"
        docker build -t nazitaog/docker-graphql:0.0.2 .
      
    - name: Push the Docker image
      run: |
        echo "Pushing the Docker image"
        docker push nazitaog/docker-graphql:0.0.2
        echo "Push realizado con exito"

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
